apiVersion: serving.knative.dev/v1
kind: Revision
metadata:
  name: basic-node-project-00001-snt
  namespace: '591182418749'
  selfLink: /apis/serving.knative.dev/v1/namespaces/591182418749/revisions/basic-node-project-00001-snt
  uid: 689a59a8-4700-44a7-88b8-d54000cf3156
  resourceVersion: AAYIld/IAnE
  generation: 1
  creationTimestamp: '2023-10-26T03:06:18.251402Z'
  labels:
    serving.knative.dev/route: basic-node-project
    serving.knative.dev/configuration: basic-node-project
    serving.knative.dev/configurationGeneration: '1'
    serving.knative.dev/service: basic-node-project
    serving.knative.dev/serviceUid: 692d4486-9ea9-4bf5-97c0-fd062b53fb40
    cloud.googleapis.com/location: asia-southeast1
    run.googleapis.com/startupProbeType: Default
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: trung.vuong@setacinq.vn
    autoscaling.knative.dev/maxScale: '100'
    run.googleapis.com/operation-id: df2b9adb-cefb-4b85-a927-256a26faa96d
    run.googleapis.com/startup-cpu-boost: 'true'
  ownerReferences:
  - kind: Configuration
    name: basic-node-project
    uid: f52f17c7-0144-40fd-85a7-4d521709df72
    apiVersion: serving.knative.dev/v1
    controller: true
    blockOwnerDeletion: true
spec:
  containerConcurrency: 80
  timeoutSeconds: 300
  serviceAccountName: 591182418749-compute@developer.gserviceaccount.com
  containers:
  - name: basic-node-project-1
    image: gcr.io/woven-operative-403115/basic-node-project@sha256:469880cf5f5f57031b459b76b0861b71dcba0badfcdbe17893cf6c0c169a8d07
    ports:
    - name: http1
      containerPort: 8000
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
    startupProbe:
      timeoutSeconds: 240
      periodSeconds: 240
      failureThreshold: 1
      tcpSocket:
        port: 8000
status:
  observedGeneration: 1
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2023-10-26T03:07:37.787157Z'
  - type: Active
    status: 'True'
    lastTransitionTime: '2023-10-26T03:07:37.844316Z'
    severity: Info
  - type: ContainerHealthy
    status: 'True'
    lastTransitionTime: '2023-10-26T03:07:37.705812Z'
  - type: ResourcesAvailable
    status: 'True'
    lastTransitionTime: '2023-10-26T03:07:35.490208Z'
    severity: Error
  logUrl: https://console.cloud.google.com/logs/viewer?project=woven-operative-403115&resource=cloud_run_revision/service_name/basic-node-project/revision_name/basic-node-project-00001-snt&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22basic-node-project%22%0Aresource.labels.revision_name%3D%22basic-node-project-00001-snt%22
  imageDigest: gcr.io/woven-operative-403115/basic-node-project@sha256:469880cf5f5f57031b459b76b0861b71dcba0badfcdbe17893cf6c0c169a8d07
  containerStatuses:
  - name: basic-node-project-1
    imageDigest: gcr.io/woven-operative-403115/basic-node-project@sha256:469880cf5f5f57031b459b76b0861b71dcba0badfcdbe17893cf6c0c169a8d07
